services:
  db:
    image: postgres:latest
    container_name: task_management_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: task_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://task_management_db:5432/task_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data:
